blog/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    # ex: /blog/
    url(r'^$', views.BlogIndexView.as_view(), name='index'),
    # ex: /blog/5/
    url(r'^(?P<article_id>[0-9]+)/$', views.ArticleDetailView.as_view(), name='article_detail'),
    url(r'^new_article/$', views.NewArticleView.as_view(), name='new_article'),
    url(r'^accounts/login/$', views.UserLoginView.as_view(), name='login'),
    url(r'^add_comment/(?P<article_id>[0-9]+)$', views.comment_add_view, name='comment_add'),
    url(r'^like_article/(?P<article_id>[0-9]+)$', views.article_like_view, name='article_like'),
    url(r'^like_comment/(?P<comment_id>[0-9]+)$', views.comment_like_view, name='comment_like'),
    url(r'^edit_article/(?P<article_id>[0-9]+)$', views.ArticleUpdateView.as_view(), name='article_update'),
    url(r'^user_articles/$', views.UserArticlesView.as_view(),name='user_articles'),
    url(r'^delete_article/(?P<article_id>[0-9]+)$',views.article_delete_view, name='article_delete'),
    url(r'^accounts/logout/$', views.user_logout_view, name='logout'),
    #url(r'^accounts/auth/', views.LoginView.as_view(), name='auth'),
    url(r'^accounts/profile/$', views.user_profile_view, name='user_profile'),
   # url(r'^account/edit_profile/(?P<pk>[0-9]+)$', views.UserUpdateView.as_view(), name='user_update'),
    url(r'^accounts/edit_profile/$', views.UserUpdateView.as_view(), name='user_update'),
    url(r'^accounts/password_change/$', views.password_change_view, name='password_change'),
    url(r'^accounts/invalid/$', views.UserLoginView.as_view(), name='login_invalid'),
    url(r'^accounts/register/$', views.UserRegisterView.as_view(), name='user_register'),
    url(r'^accounts/register_success/$', TemplateView.as_view(template_name="blog/register_success.html"), name='register_success'),
    url(r'^search/$', views.articles_search_view, name='articles_search')
    # temp
    #url(r'^your-name/', views.get_name, name = 'get_name'),
    #url(r'^thanks/', views.thanks_for_name),
    #url(r'^contact/', views.contact),
    #url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    ]

shmarlovski_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
#from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
#from django.conf import settings
#from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="index.html"), name='index'),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^about/$', TemplateView.as_view(template_name="about.html"), name='about'),
    #url('^', include('django.contrib.auth.urls')),
    url(r'^admin/', include(admin.site.urls)),
] #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models

from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

# class User(AbstractBaseUser):
# 	username = models.CharField('username', max_length=30, unique=True)
# 	email =	models.EmailField('email address', unique=True)
# 	firstname = models.CharField('first name', max_length=30)
# 	lastname = models.CharField('last name', max_length=30)
# 	joined = models.DateTimeField(auto_now_add=True)
# 	is_active=models.BooleanField(default=True)
# 	is_admin = models.BooleanField(default=False)
# 	USERNAME_FIELD = 'username'

# 	def __str__(self):
# 		return	self.username


class Article(models.Model):
    headline = models.CharField(max_length=200)
    content = models.TextField()
    pub_date = models.DateTimeField('date published', default=timezone.now())
    author = models.ForeignKey(User)
    likes = models.IntegerField(default=0)

    def __str__(self):
        return self.headline


class Comment(models.Model):
    article = models.ForeignKey(Article)
    content = models.TextField(max_length=30)
    pub_date = models.DateTimeField('date published', default=timezone.now())
    author = models.ForeignKey(User)
    likes = models.IntegerField(default=0)

    def __str__(self):
        return self.content

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext, ugettext_lazy as _
from .models import Article, Comment
from django.forms import widgets
from django.views.generic.edit import FormView

class MyFormView(FormView):
    error_css_class = 'class-error'
    required_css_class = 'class-required'

    def __init__(self, *args, **kwargs):
        super(MyFormView, self).__init__(*args, **kwargs)
        # adding css classes to widgets without define the fields:
        #for field in self.fields:
        #    self.fields[field].widget.attrs['class'] = 'some-class other-class'

    def as_div(self):
        return self._html_output(
            normal_row = u'<div%(html_class_attr)s>%(label)s %(field)s %(help_text)s %(errors)s</div>',
            error_row = u'<div class="error">%s</div>',
            row_ender = '</div>',
            help_text_html = u'<div class="help-text">%s</div>',
            errors_on_separate_row = False)


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

class ArticleForm(forms.ModelForm):
    headline = forms.CharField()
    content = forms.CharField(widget=forms.Textarea(attrs={'cols': 50, 'rows': 10}), label='Content')
    class Meta:
        model = Article
        fields = ['headline', 'content']

class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'cols': 40, 'rows': 4}), label='')
    class Meta:
        model = Comment
        fields = ['content']
        # widgets = {
        #     'content': forms.Textarea(attrs={'cols': 40, 'rows': 4}),
        # }

class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=30)
    password = forms.CharField(max_length=30, label="Password", widget=forms.PasswordInput)

class BlogRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    # error_messages = {
    #     'password_mismatch': _("The two password fields didn't match."),
    # }

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name')

    # def as_div(self):
    #     return self._html_output(
    #         normal_row = u'<div%(html_class_attr)s>%(label)s %(field)s %(help_text)s %(errors)s</div>',
    #         error_row = u'<div class="error">%s</div>',
    #         row_ender = '</div>',
    #         help_text_html = u'<div class="help-text">%s</div>',
    #         errors_on_separate_row = False)

    def save(self, commit=True):
        user=super(BlogRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
        return user


class SearchForm(forms.Form):
    search = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from django.views import generic
from django.views.generic.edit import FormView
from django.views.generic.edit import UpdateView
from django.http import HttpResponseRedirect
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.views import password_change
from django.utils.decorators import method_decorator
from django.core.context_processors import csrf
from django.core.urlresolvers import reverse
from django.utils import timezone

from .models import Article, Comment
from .forms import LoginForm, BlogRegistrationForm, ArticleForm, CommentForm, MyFormView, SearchForm


class BlogIndexView(generic.ListView):
    template_name = 'blog/blog_index.html'
    context_object_name = 'latest_articles_list'

    def get_context_data(self, **kwargs):
        context = super(BlogIndexView, self).get_context_data(**kwargs)
        context['search_form'] = SearchForm()
        context.update(csrf(self.request))
        return context

    #return articles sorted by date
    def get_queryset(self):
        return Article.objects.order_by('-pub_date')


class ArticleDetailView(generic.DetailView):
    model = Article
    template_name = 'blog/article.html'
    pk_url_kwarg = 'article_id'

    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            context['comment_form'] = CommentForm()
        context['search_form'] = SearchForm()
        context.update(csrf(self.request))
        return context


class NewArticleView(FormView):
    """ For creating new article/ Available only for registered users
    """
    template_name = 'blog/new_article.html'
    form_class = ArticleForm
    success_url = '/blog/'

    @method_decorator(login_required(login_url='/blog/accounts/login/'))
    def dispatch(self, *args, **kwargs):
        return super(NewArticleView, self).dispatch(*args, **kwargs)

    # def get(self, request):
    #     args = {}
    #     args.update(csrf(request))
    #     # return render(request, self.template_name, c)
    #     return super(NewArticleView, self).get(args)

    def form_valid(self, form):
        #form.save()
        new_article = Article()
        new_article.headline = self.request.POST.get('headline', '')
        new_article.content = self.request.POST.get('content', '')
        new_article.pub_date = timezone.now()
        new_article.author = self.request.user
        new_article.save()
        return HttpResponseRedirect(reverse('blog:index'))


class ArticleUpdateView(UpdateView):
    """ For editing article by certain user. Available only for registered users
    """
    model = Article
    fields = ['headline', 'content']
    template_name = 'blog/article_update.html'
    success_url = '/blog/user_articles/'
    pk_url_kwarg = 'article_id'

    @method_decorator(login_required(login_url='/blog/accounts/login/'))
    def dispatch(self, *args, **kwargs):
        return super(ArticleUpdateView, self).dispatch(*args, **kwargs)


@login_required(login_url='/blog/accounts/login')
def article_like_view(request, article_id):
    if request.user.is_authenticated():
        if article_id:
            a = Article.objects.get(pk=article_id)
            a.likes += 1
            a.save()
        return HttpResponseRedirect(reverse('blog:article_detail', args=[article_id]))


@login_required(login_url='/blog/accounts/login')
def article_delete_view(request, article_id):
    if request.user.is_authenticated():
        if article_id:
            article = Article.objects.get(pk=article_id)
            article.delete()
            return HttpResponseRedirect(reverse('blog:user_articles'))


@login_required(login_url='/blog/accounts/login')
def comment_like_view(request, comment_id):
    if request.user.is_authenticated():
        if comment_id:
            c = Comment.objects.get(pk=comment_id)
            c.likes += 1
            c.save()
            article_id = str(c.article_id)
    return HttpResponseRedirect(reverse('blog:article_detail', args=[article_id]))


@login_required(login_url='/blog/accounts/login')
def comment_add_view(request, article_id):
    if request.POST:
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = Comment()
            new_comment.author = request.user
            new_comment.content = request.POST.get('content')
            article = get_object_or_404(Article, pk=article_id)
            new_comment.article = article
            new_comment.save()
            return HttpResponseRedirect(reverse('blog:article_detail', args=[article_id]))
        else:
            return HttpResponseRedirect(reverse('blog:article_detail', args=[article_id]))
    else:
        return HttpResponseRedirect(reverse('blog:article_detail', args=[article_id]))


class UserLoginView(FormView):
    template_name = 'blog/login.html'
    form_class = LoginForm
    success_url = '/blog/accounts/profile/'

    # def get(self, request):
    #     args = {}
    #     args.update(csrf(request))
    #     # return render(request, self.template_name, c)
    #     return super(UserLoginView, self).get(args)

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        username = self.request.POST.get('username', '')
        password = self.request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                auth.login(self.request, user)
                return super(UserLoginView, self).form_valid(form)
        else:
            return render(self.request, "blog/invalid.html")


class UserRegisterView(MyFormView):
    template_name = 'blog/register.html'
    form_class = BlogRegistrationForm
    success_url = '/blog/accounts/register_success/'

    # def get(self, request):
    #     args = {}
    #     args.update(csrf(request))
    #     # return render(request, self.template_name, c)
    #     return super(UserRegisterView, self).get(args)

    def get_context_data(self, **kwargs):
        context = super(UserRegisterView, self).get_context_data(**kwargs)
        #context['search_form'] = SearchForm()
        context.update(csrf(self.request))
        return context

    def form_valid(self, form):
        form.save()
        return super(UserRegisterView, self).form_valid(form)


class UserUpdateView(UpdateView):
    model = User

    fields = ['username', 'email', 'first_name', 'last_name']
    template_name = 'blog/user_update.html'
    success_url = '/blog/accounts/profile/'

    @method_decorator(login_required(login_url='/blog/accounts/login/'))
    def dispatch(self, *args, **kwargs):
        return super(UserUpdateView, self).dispatch(*args, **kwargs)

    def get_object(self, queryset=None):
        if self.request.user.is_authenticated():
            user = User.objects.get(pk=self.request.user.id)
            return user


@login_required(login_url='/blog/accounts/login')
def user_profile_view(request):
    if request.user.is_authenticated():
        return render(request, "blog/profile.html", {'user': request.user})


@login_required(login_url='/blog/accounts/login')
def password_change_view(request):
    return password_change(request, template_name='blog/password_change.html',
                           post_change_redirect=reverse('blog:user_profile'))


class UserArticlesView(generic.ListView):
    template_name = 'blog/user_articles.html'
    context_object_name = 'user_articles_list'

    @method_decorator(login_required(login_url='/blog/accounts/login/'))
    def dispatch(self, *args, **kwargs):
        return super(UserArticlesView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        articles = Article.objects.filter(author__username=self.request.user)
        return articles.order_by('-pub_date')


def user_logout_view(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('blog:index'))


def articles_search_view(request):
    if request.method == 'POST' and request.POST['search_text'] != '':
        search_text = request.POST['search_text']
    else:
        articles = {}
        return render_to_response('blog/search_articles.html', {'articles': articles})

    articles = Article.objects.filter(headline__icontains=search_text)
    # return render(request, 'blog/search_articles.html', {'articles': articles})
    return render_to_response('blog/search_articles.html', {'articles': articles})

blog/templates/blog/article.html
{% extends "blog/blog_index.html" %}
{% load bootstrap3 %}
{% block title %}
    Blog: {{ article.headline }}
{% endblock %}

{% block main_info %}
    <h1 class="article_headline">{{ article.headline }}</h1>
    {% if error_message %}
        <p>{{ error_message }}</p>
    {% endif %}
    <br>
    <p id="article_content">
        {{article.content|safe}}
    </p>
    <br>
    <p> By {{ article.author }} </p>
    <p> {{ article.pub_date }}</p>

    <form action="{% url 'blog:article_like' article.id %}">
        {% if user.is_authenticated %}
        {% buttons %}
            {{ article.likes }} people like it
            <button type="submit" class="btn">
                {% bootstrap_icon "heart" %}
            </button>
        {% endbuttons %}
    {% endif %}
    </form>

    <br>

    {% for comment in article.comment_set.all %}
        <ul>
            <li>
                <form action="{% url 'blog:comment_like' comment.id %}">
                        <p id="comment_author"> {{ comment.author }}: </p>

                        {% buttons %}
                            <Strong> {{ comment.content }} </Strong> | {{ comment.likes }} like it
                            {% if user.is_authenticated %}
                        <button type="submit" class="btn" >{% bootstrap_icon "heart" %}</button>
                            {%  endif %}
                        {% endbuttons %}



                </form>

                <p>  </p>
            </li>
        </ul>

    {% endfor %}

    {% if user.is_authenticated %}
    <form action="{% url 'blog:comment_add' article.id %}" method="post">
        {% csrf_token %}
        {% bootstrap_form comment_form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary">Add comment
            </button>
        {% endbuttons %}

    </form>
    {% endif %}


{% endblock  %}

blog/templates/blog/article_update.html
{% extends 'blog/base_blog.html' %}
{% load bootstrap3 %}

{% block title %}
    Blog: edit article
{% endblock %}

{% block main_info %}

    <form action="" method="post">{% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Update
            </button>
        {% endbuttons %}
    </form>

{% endblock %}

{% block sidebar %}
    <p align="right"><a href="{% url 'blog:user_articles' %}"> Cancel</a> </p>
{% endblock %}

{% block js %}
    <script src="http://js.nicedit.com/nicEdit-latest.js" type="text/javascript"></script>
    <script type="text/javascript">bkLib.onDomLoaded(nicEditors.allTextAreas);</script>
{% endblock %}

blog/templates/blog/base_blog.html
{% extends "base.html" %}
{% block title %}
    Blog
{% endblock %}

{% block menu %}
    <li><a href="{% url 'blog:index' %}"> Blog </a></li>
    {% if user.username == "admin" %}
        <li><a href="/admin"> Admin </a></li>
    {% endif %}
    <li><a href="{% url 'about' %}"> About</a>
{% endblock menu %}

{% block content %}

    <div class="row">
        <div class="col-md-8">
            {% block main_info %}
            {% endblock %}
        </div>

        <div class="col-md-4">
            {% block sidebar %}
            {% endblock %}
        </div>
    </div> <!-- row -->

{%  endblock %}

blog/templates/blog/blog_index.html
{% extends "blog/base_blog.html" %}
{% load bootstrap3 %}
{% block main_info %}
    {% if latest_articles_list %}
        <div class="row clearfix">
                {% for article in latest_articles_list %}
                    <div class="well">
                        <a id="articles_list" href="{% url 'blog:article_detail' article.id %}">{{ article.headline }}</a>
                    </div>
                {% endfor %}
        </div>
    {% elif user.is_authenticated %}
        <h4 align="center">No articles.</h4>
    {% else %}
        <h4 align="center">To see articles please log in.</h4>
    {% endif %}
{%  endblock %}
<!--
<div class="col-md-4">
    <form class="form-horizontal" id="sign_in_form">
      <div class="form-group">
        <label for="inputEmail" class="col-sm-4 control-label">Username</label>
        <div class="col-sm-8">
          <input type="text" class="form-control" id="inputEmail" placeholder="Username">
      </div>
  </div>
  <div class="form-group">
    <label for="inputPassword" class="col-sm-4 control-label">Password</label>
    <div class="col-sm-8">
      <input type="password" class="form-control" id="inputPassword" placeholder="Password">
  </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-4 col-sm-8">
      <button type="submit" class="btn btn-default">Sign in</button>
      <button type="submit" class="btn btn-default">Register</button>
  </div>
</div>
</form>

</div>
-->
{% block sidebar %}

    <div class="sidebar">
        {% if user.is_authenticated %}
            <p> Hello, <a href="{% url 'blog:user_profile' %}"> {{ user.username }} </a></p>
            <a href="{% url 'blog:new_article' %}">Create Article</a> <br>
            <a href="{% url 'blog:logout' %}"> Log out </a> <br>
            <br>
        {% else %}
            <a href="{% url 'blog:login' %}"> Log in </a> <br>
            <a href="{% url 'blog:user_register' %}"> Register </a>
            <br> <br>
            {% csrf_token %}
            {% bootstrap_field search_form.search show_label=False %}
            <p id="search-results"> </p>
            </div>
        {% endif %}
    </div>
{%  endblock %}

blog/templates/blog/invalid.html
{% extends "blog/base_blog.html" %}

{% block content %}
<div class="container" align = "center">
    <p align="center"> Invalid data </p>
    <a align ="center" href="{% url 'blog:login' %}"> Try again </a>
</div>
{% endblock content %}

blog/templates/blog/login.html
{% extends "blog/base_blog.html" %}
{% load bootstrap3 %}
{% block title %}
    Blog: Login
{% endblock title %}

{% block main_info %}
    <div class="login_form" align="left">
        <form action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">Log in
                </button>
                <button type="reset" class="btn">Clear
                </button>
            {% endbuttons %}
        </form>
    </div>
{% endblock  %}

{% block sidebar %}
    <p align="right"><a href="{% url 'blog:index' %}"> Cancel</a> </p>
{% endblock %}

blog/templates/blog/new_article.html
{% extends "blog/base_blog.html" %}
{% load bootstrap3 %}
{% block main_info %}
    <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Submit
            </button>
        {% endbuttons %}
    </form>

{% endblock %}

{% block sidebar %}
    <p align="right"> <a href="{% url 'blog:index' %}">Cancel</a> </p>
{%  endblock %}

<!-- {#  {% block js %} #}
    <script src="http://js.nicedit.com/nicEdit-latest.js" type="text/javascript"></script>
    <script type="text/javascript">bkLib.onDomLoaded(nicEditors.allTextAreas);</script
-->

blog/templates/blog/password_change.html
{% extends 'blog/base_blog.html' %}
{% load bootstrap3 %}
{%  block title %}
    Blog: Password change
{% endblock %}

{% block main_info %}
    <form action="" method="post">{% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Update
            </button>
        {% endbuttons %}
    </form>
{% endblock %}

{% block sidebar %}
    <p align="right"><a href="{% url 'blog:user_profile' %}"> Cancel</a> </p>
{% endblock %}

blog/templates/blog/profile.html
{% extends "blog/base_blog.html" %}

{% block main_info %}
    <div class="user_info">
        <p> <strong>Username: </strong> {{ user.username }}</p>
        <p> <strong> First name: </strong> {{ user.first_name }}</p>
        <p> <strong> Last name: </strong> {{ user.last_name }}</p>
        <p> <strong> Email: </strong> {{ user.email }} </p>
        <a href="{% url 'blog:user_articles' %}"> My articles </a> <br>
        <a href="{% url 'blog:user_update' %}"> Edit user</a> <br>
        <a href="{%  url 'blog:password_change' %}">Change Password</a> <br>
        <a href = "{% url 'blog:logout' %}" > Log out </a>
    </div>
{% endblock  %}

blog/templates/blog/register.html
{% extends "blog/base_blog.html" %}

{% load bootstrap3 %}
{% block title %}
    Registration
{% endblock title %}

{% block main_info %}

    <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Register
            </button>
            <button type="reset" class="btn">Clear
            </button>
        {% endbuttons %}
    </form>

{% endblock main_info %}

{% block sidebar %}
    <p align="right"><a href="{% url 'blog:index' %}"> Cancel</a> </p>
{% endblock %}

blog/templates/blog/register_success.html
{% extends "blog/base_blog.html" %}
{% block title %}
    Registration completed
{% endblock title %}

{% block main_info %}
    <p>Thanks for registration <br>
        <a href="{% url "blog:login" %}" >Now you can log in </a>
    </p>

    </div>
{% endblock main_info %}

blog/templates/blog/search_articles.html
{% if articles.count > 0 %}

    {% for article in articles %}
    <p><a href="{% url 'blog:article_detail' article.id %}"> {{ article.headline }} </a></p>
    {% endfor %}

{% else %}
    <p> No results </p>
{% endif %}

blog/templates/blog/user_articles.html
{% extends 'blog/base_blog.html' %}
{% load bootstrap3 %}

{% block title %}
    Blog: my articles
{% endblock %}

{% block main_info %}

    {% if user_articles_list %}
        <div class="row clearfix">

                {% for article in user_articles_list %}
                    <div class="well">
                      <p>  <a href="{% url 'blog:article_update' article.id %}">{{ article.headline }}</a>
                      <a class="delete_link" href="{% url 'blog:article_delete' article.id %}"> Delete </a> </p>
                    </div>

                {% endfor %}

        </div>
    {% else %}
        <h4 align="center">No articles.</h4>
    {% endif %}

{% endblock %}

{% block sidebar %}
    <p align="right"><a href="{% url 'blog:user_profile' %}"> Cancel</a> </p>
{% endblock %}

blog/templates/blog/user_update.html
{% extends 'blog/base_blog.html' %}
{% load bootstrap3 %}
{% block title %}
    Blog: edit user
{%  endblock %}

{%  block main_info %}
    <form action="" method="post">{% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Update
            </button>
        {% endbuttons %}
    </form>

{%  endblock %}

{% block sidebar %}
    <p align="right"><a href="{% url 'blog:user_profile' %}"> Cancel</a> </p>
{% endblock %}