blog/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    # ex: /blog/
    url(r'^$', views.BlogIndexView.as_view(), name='index'),
    # ex: /blog/5/
    url(r'^(?P<article_id>[0-9]+)/$', views.ArticleDetailView.as_view(), name='article_detail'),
    url(r'^new_article/$', views.NewArticleView.as_view(), name='new_article'),
    url(r'^accounts/login/$', views.UserLoginView.as_view(), name='login'),
    url(r'^add_comment/(?P<article_id>[0-9]+)$', views.comment_add_view, name='comment_add'),
    url(r'^like_article/(?P<article_id>[0-9]+)$', views.article_like_view, name='article_like'),
    url(r'^like_comment/(?P<comment_id>[0-9]+)$', views.comment_like_view, name='comment_like'),
    url(r'^edit_article/(?P<article_id>[0-9]+)$', views.ArticleUpdateView.as_view(), name='article_update'),
    url(r'^user_articles/$', views.UserArticlesView.as_view(),name='user_articles'),
    url(r'^delete_article/(?P<article_id>[0-9]+)$',views.article_delete_view, name='article_delete'),
    url(r'^accounts/logout/$', views.user_logout_view, name='logout'),
    #url(r'^accounts/auth/', views.LoginView.as_view(), name='auth'),
    url(r'^accounts/profile/$', views.user_profile_view, name='user_profile'),
   # url(r'^account/edit_profile/(?P<pk>[0-9]+)$', views.UserUpdateView.as_view(), name='user_update'),
    url(r'^accounts/edit_profile/$', views.UserUpdateView.as_view(), name='user_update'),
    url(r'^accounts/password_change/$', views.password_change_view, name='password_change'),
    url(r'^accounts/invalid/$', views.UserLoginView.as_view(), name='login_invalid'),
    url(r'^accounts/register/$', views.UserRegisterView.as_view(), name='user_register'),
    url(r'^accounts/register_success/$', TemplateView.as_view(template_name="blog/register_success.html"), name='register_success'),
    url(r'^search/$', views.articles_search_view, name='articles_search')
    # temp
    #url(r'^your-name/', views.get_name, name = 'get_name'),
    #url(r'^thanks/', views.thanks_for_name),
    #url(r'^contact/', views.contact),
    #url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    ]

shmarlovski_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
#from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
#from django.conf import settings
#from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="index.html"), name='index'),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^about/$', TemplateView.as_view(template_name="about.html"), name='about'),
    #url('^', include('django.contrib.auth.urls')),
    url(r'^admin/', include(admin.site.urls)),
] #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/about.html
{% extends "base.html" %}

{% block title %}
    Blog: About
{% endblock %}

{% block menu %}
    <li><a href="{% url 'index' %}">Home</a></li>
    <li><a href="{% url 'blog:index' %}">Blog</a></li>
{% endblock menu %}

{%block content %}
    <div id="about_info">
    Created with Django 1.8.2 <br> <br>
    Contact info: kiril@shmarlovski.by </div>

{% endblock %}

templates/base.html
{% load staticfiles %}
{% load bootstrap3 %}
{% bootstrap_messages %}

<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {# <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags --> #}
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen" />
    <link href="{% static 'style.css' %}" rel="stylesheet" media="screen" />
</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">Shmarlovsky</a>
      </div>

      <div id="menu" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
          {% block menu %}

          {% endblock %}
        </ul>
    </div><!--/.nav-collapse -->
</div>
</nav>

<div class="container">
    {% block content %}

    {% endblock%}
</div>

<nav class="navbar navbar-inverse navbar-fixed-bottom">

</nav>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> -->
<script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
<!--<script src="{% static 'js/bootstrap.min.js' %}"></script> -->
<script src="{% static 'js/ajax.js' %}"></script>
{% block js %}
{% endblock %}
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block title %} Shmarlovsky {% endblock %}

{% block menu %}
    <li><a href="{% url 'blog:index' %}">Blog</a></li>
    <li><a href="{% url 'about' %}">About</a></li>
{% endblock menu %}

{%block content %}
<p align=center> <a href="{% url 'blog:index' %}"> BLOG </a></p>
<h4 align=center> This site was created for learning web development </h4>

{% endblock %}